tensorchord/envd-docs

docs/get-started.md
docs/why/why.md

fix: Fix according to https://github.com/tensorchord/envd/pull/305

---

.github/workflows/update_api_doc.yaml

Signed-off-by: Jinjing.Zhou <allenzhou@tensorchord.ai>

bug: fix github action pr process

---

docs/community/roadmap.md
sidebars.js

chore: Add roadmap

---

docs/build-envd/build-envd.md
docs/tips/mirror.md
sidebars.js

Fix https://github.com/tensorchord/envd/issues/424

chore: Add mirror

---

docs/concepts.md
sidebars.js

chore: Add concepts

---

docs/get-started.md

fix: Remove --pre

---

docs/community/contributing.md

See https://github.com/tensorchord/envd/pull/456.

docs: Update link and text regarding code of conduct

---

docs/api/config.md
docs/community/roadmap.md
docs/concepts.md
docs/get-started.md
docs/tips/mirror.md

Signed-off-by: Zhizhen He <hezhizhen.yi@gmail.com>

chore: fix typo

---

docs/get-started.md

Signed-off-by: Duan Fei [hi@duanfei.org](mailto:hi@duanfei.org)
#53

typo(doc):fix 'guides' link

---

docs/get-started.md
docs/lang/python.md
sidebars.js

feat: Add python lang guide

---

i18n/zh/docusaurus-plugin-content-docs/current/concepts.md

Signed-off-by: Duan Fei [hi@duanfei.org](mailto:hi@duanfei.org)
Hi，Hi guys, I have tried to translate the `concepts`chapter.
ps:I am not familiar with this technology, so please correct me if there is any improper translation,thanks

docs(concepts):Chinese version

---

docusaurus.config.js

Signed-off-by: shaoanianche <duanfei.job@gmail.com>

chore(docusaurus):add domain

---

docs/lang/r.md
sidebars.js

Part of https://github.com/tensorchord/envd/issues/509.
Signed-off-by: Yuan Tang <terrytangyuan@gmail.com>

docs: Add R language specific guide

---

docs/lang/julia.md
docs/lang/r.md

feat(lang): Add julia and fix R

---

sidebars.js

fix: Add Julia

---

docs/ide/ide.md

fix: Fix title case

---

docs/get-started.md

Signed-off-by: nullday <aseaday@hotmail.com>

feat: Add notice for root users

---

docs/build-envd/build-envd.md
docs/concepts.md
docs/get-started.md
docs/ide/ide.md
docs/lang/python.md
docs/why/why.md
i18n/zh/docusaurus-plugin-content-docs/current/build-envd/build-envd.md
i18n/zh/docusaurus-plugin-content-docs/current/concepts.md
i18n/zh/docusaurus-plugin-content-docs/current/get-started.md
i18n/zh/docusaurus-plugin-content-docs/current/why/why.md

feat: Remove jupyter port

---

docs/tips/config.md
sidebars.js

Fix https://github.com/tensorchord/envd-docs/issues/7

chore: Add config

---

docs/lang/python.md

Signed-off-by: Qi Chen <aseaday@hotmail.com>

feat: Add docs for python version

---

docs/get-started.md
i18n/zh/docusaurus-plugin-content-docs/current/get-started.md

Ref https://github.com/tensorchord/envd/issues/621

fix: Use pre release

---

docs/ide/ide.md
docs/tips/cache.md
sidebars.js

feat: Add remote cache

---

i18n/zh/docusaurus-plugin-content-docs/current/community/contributing.md

translate contributing page to Chinese

translate contributing page to zh

---

docs/index.md
tsconfig.json

Signed-off-by: Jinjing.Zhou <allenzhou@tensorchord.ai>
Also add tsconfig.json to support intellisense

doc: Minor fix 

---

docs/zh/community/contributing.md
docs/zh/community/development.md

chore: fix spaces between Chinese and English chars

---

docs/.vitepress/config.ts

feat: add algolia search bar

---

README.md
docs/.vitepress/config.ts
docs/.vitepress/config/sidebar.ts
docs/blog/welcome.md

- when you add the first post to the blog you need add the default link to the 
`docs/.vitepress/config.ts` `nav`
- when add new post you should do following the readme blog
the Blog page will looks like

feat: blog page

---

docs/.vitepress/components/Author.vue
docs/.vitepress/theme/index.ts
docs/blog/welcome.md
tsconfig.json

feat: author component

---

docs/.vitepress/config.ts

feat: improve seo

---

docs/guide/getting-started.md

Signed-off-by: zhenguo.li <zhenguo.li@shopee.com>

docs(guide): sync getting-started from envd repository

---

docs/.vitepress/config.ts

feat: add releases nav link

---

docs/.vitepress/config/sidebar.ts
docs/.vitepress/theme/custom.css
docs/tips/comparison.md
docs/tips/context.md
docs/zh/tips/comparison.md
docs/zh/tips/context.md

feat(docs): Add context doc and update comparison

---

hack/api/render.py

Signed-off-by: Jinjing.Zhou <allenzhou@tensorchord.ai>
Method will use header 2 instead of header 4 for the title.

style: Minor style improvement for generated API doc

---

docs/.vitepress/config/sidebar/main.ts
docs/.vitepress/config/sidebar/zh.ts
docs/tips/monitoring.md
docs/zh/tips/monitoring.md

* fix https://github.com/tensorchord/envd/issues/527

feat: add monitoring doc

---

docs/.vitepress/theme/index.ts
index.d.ts

chore: enhance type

---

docs/.vitepress/components/Author.vue
docs/zh/index.md
package.json
pnpm-lock.yaml
tsconfig.json

chore: bump up to alpha.9

---

docs/faq/why.md

fix: Fix typo

---

.vscode/settings.json
docs/zh/envs/mirror.md
netlify.toml
pnpm-lock.yaml

Signed-off-by: shaoanianche <github@duanfei.org>

docs(chinese):mirror

---

docs/envs/monitoring.md
docs/envs/multitarget.md
docs/guide/build-envd.md
docs/zh/envs/monitoring.md
docs/zh/guide/build-envd.md

* related to https://github.com/tensorchord/envd/pull/853

refact: apt_source, io, config mode

---

docs/.vitepress/config/sidebar/blog.ts
docs/zh/blog/envd.md

feat: Add envd intro blog post in Chinese

---

docs/zh/blog/envd.md

fix: Update demo

---

docs/envs/monitoring.md
docs/zh/envs/monitoring.md

* related to https://github.com/tensorchord/envd/pull/861

refact: io.mount => runtime.mount

---

docs/community/development.md
docs/zh/community/development.md

Upstream PR: https://github.com/tensorchord/envd/pull/866

chore: Update docs for envd-sshd

---

docs/.vitepress/config/sidebar/blog.ts
docs/zh/blog/stable-diffusion-cpu.md

feat: Add sd-cpu post

---

docs-zh/.vitepress/config.ts
docs-zh/.vitepress/config/sidebar/blog.ts

fix: Fix chinese blog

---

OWNERS

chore: Add owners

---

docs-zh/envs/monitoring.md

Signed-off-by: shaoanianche <github@duanfei.org>

docs:chinese version

---

docs-zh/netlify.toml

fix: Fix chinese website CI

---

docs-zh/blog/envd.md

Use include feature to illustrate the benefits for teams.

fix(envd-blog-post): Fix team section

---

docs-zh/guide/ide.md

fix: Add expose section in Chinese

---

docs/.vitepress/config/sidebar/blog.ts
docs/blog/ml-env.md
pnpm-lock.yaml

doc: add en ML env post

---

docs/blog/ml-env.md

Signed-off-by: Nino <lilylee1874@outlook.com>

doc: add comic to post

---

docs/blog/ml-env.md

Signed-off-by: Nino lilylee1874@outlook.com

update comic 2

---

docs-zh/blog/envd.md
docs-zh/envs/multitarget.md
docs-zh/faq/why.md
docs-zh/guide/build-envd.md
docs-zh/tips/multitarget.md
docs/blog/ml-env.md
docs/faq/why.md
docs/guide/build-envd.md

fix: cuda version

---

docs/blog/hacktoberfest.md

* display: swap
* minimize the font size
* adjust line height to make sure fallback font can be displayed normally

fix: hacktoberfest font display

---

docs-zh/blog/envd.md
docs-zh/envs/multitarget.md
docs-zh/faq/why.md
docs-zh/guide/build-envd.md
docs-zh/tips/multitarget.md
docs/blog/ml-env.md
docs/faq/why.md
docs/guide/build-envd.md

* related to https://github.com/tensorchord/envd/pull/951

chore: fix cuda & cudnn version in the examples

---

docs-zh/.vitepress/config/sidebar/blog.ts
docs-zh/blog/hacktoberfest.md

feat: Add hacktoberfest blog post in Chinese

---

Makefile
pnpm-lock.yaml

chore: update cmd in makefile

---

docs-zh/teams/ci.md

chore: translate team ci

---

docs-zh/teams/cache.md
docs/teams/cache.md

chore: translate team cache

---

docs-zh/teams/context.md

Although the context doc is already outdated. :)
We can update the en/zh doc later.

chore: translate team context

---

docs-zh/teams/ci.md
docs/teams/ci.md

feat(ci): Support daemonless

---

README.md

Capitalize first character on README file
Signed-off-by: MyFRA <tomyntapss@gmail.com>

docs: Improvement README

---

docs-zh/community/development.md
docs/community/development.md

fix: #177 
Signed-off-by: dqhl76 <dqhl76@gmail.com>

fix: Fix version flag

---

docs-zh/blog/envd.md
docs-zh/community/development.md
docs-zh/envs/multitarget.md
docs-zh/faq/why.md
docs-zh/guide/build-envd.md
docs-zh/tips/multitarget.md
docs/blog/ml-env.md
docs/community/development.md
docs/faq/why.md
docs/guide/build-envd.md

chore: update cuda & cudnn version, update dev guide

---

docs-zh/community/roadmap.md
docs/community/roadmap.md

fix: Updated roadmap

---

docs-zh/blog/stable-diffusion-cpu.md

/cc @xieydd
/assign @kemingy @VoVAllen 

fix: Fix script in SD

---

docs/.vitepress/config/sidebar/main.ts
docs/teams/context.md
docs/teams/kubernetes.md

chore: Add kubernetes doc

---

.github/workflows/api_doc.yaml
.gitignore
Makefile
hack/api/render.py

* close https://github.com/tensorchord/envd-docs/issues/142
test in https://github.com/kemingy/envd-docs/actions/runs/3521356803

feat: support envdlib

---

.github/workflows/api_doc.yaml
hack/api/render.py

doc: add v1 doc, refactor render logic

---

docs-zh/developer/development.md
docs-zh/envs/monitoring.md
docs-zh/guide/build-envd.md
docs/developers/development.md
docs/envs/mirror.md
docs/envs/monitoring.md
docs/guide/build-envd.md
docs/guide/concepts.md
hack/api/render.py

fix: fix new v0/lib url

---

docs-zh/.vitepress/components/Tabs/Tab.vue
docs-zh/.vitepress/components/Tabs/Tabs.vue
docs-zh/.vitepress/components/Tabs/expiringStorage.ts
docs-zh/.vitepress/theme/custom.css
docs-zh/.vitepress/theme/index.ts
docs-zh/guide/getting-started.md
docs/.vitepress/components/Tabs/Tab.vue
docs/.vitepress/components/Tabs/Tabs.vue
docs/.vitepress/components/Tabs/expiringStorage.ts
docs/.vitepress/theme/custom.css
docs/.vitepress/theme/index.ts
docs/guide/getting-started.md
docs/public/install.sh
package.json
pnpm-lock.yaml

- Add a (simple) installation script to the root of the website so that one can install envd with one command, without any tool except for `curl`
- Update the docs and chinese docs to list several installation methods
Resolve #204

docs: improve the installation guide in getting start page

---

docs/.vitepress/config.ts

Signed-off-by: Jinjing.Zhou <allenzhou@tensorchord.ai>

bug: fix footer

---

docs/.vitepress/config/sidebar/blog.ts
docs/blog/pycon2022.md

add pycon china 2022 slides

---

docs/teams/kubernetes.md

fix: Fix kubernetes page

---

docs/teams/kubernetes.md

feat: Add image pull secret

---

docs-zh/api/starlark/runtime.md
docs-zh/api/starlark/v0/runtime.md
docs-zh/api/starlark/v1/runtime.md
docs-zh/developer/kubernetes.md
docs/api/starlark/runtime.md
docs/api/starlark/v0/runtime.md
docs/api/starlark/v1/runtime.md
docs/developers/kubernetes.md
docs/teams/kubernetes.md

Signed-off-by: Keming <kemingy94@gmail.com>

fix: rename run to exec, create to run

---

docs-zh/.vitepress/config.ts

Signed-off-by: han <suyanhanx@gmail.com>

docs(zh): modify some locale theme config

---

docs-zh/.vitepress/config.ts
docs/.vitepress/config.ts
package.json
pnpm-lock.yaml

closing: #238 
Signed-off-by: han <suyanhanx@gmail.com>

docs: feat sitemap

---

docs-zh/blog/2022.md
docs/blog/2022.md

Signed-off-by: Keming <kemingy94@gmail.com>

fix: 2022 retro code format

---

docs-zh/public/robots.txt
docs/public/robots.txt

Signed-off-by: han <suyanhanx@gmail.com>

feat: add robots.txt

---

docs-zh/.vitepress/config.ts
docs/.vitepress/config.ts

feat: support dyanmic og

---

docs-zh/.vitepress/config.ts
docs/.vitepress/config.ts

feat: add open graph image

---

docs-zh/guide/getting-started.md
docs/guide/getting-started.md

https://github.com/tensorchord/envd-quick-start/blob/master/build.envd
envd file has changed, docs are not synced

guide: update getting-started.md, unified with real file content

---

docs-zh/guide/concepts.md
docs-zh/guide/getting-started.md
docs-zh/teams/cache.md

Signed-off-by: han <suyanhanx@gmail.com>

docs: sync from en

---

docs-zh/.vitepress/config/sidebar/blog.ts
docs-zh/blog/envd-server.md
docs/.vitepress/config/sidebar/blog.ts
docs/blog/envd-server.md

add new blog to introduce envd server

---

hack/api/render.py

fix https://github.com/tensorchord/envd-docs/pull/262#issuecomment-1397866336

fix the order of generated config items

---

docs-zh/teams/context.md
docs/teams/context.md

* fix https://github.com/tensorchord/envd-docs/issues/253

add buildkitd cache config

---

docs-zh/developers/development.md
docs/developers/development.md

update the development tutorial

---

docs/.vitepress/config/sidebar/main.ts
docs/community/gsoc.md

add GSoC page

---

docs-zh/developers/development.md
docs/developers/development.md

docs: Improve dev guide description and link

---

docs-zh/blog/mloops-e01.md
docs-zh/tips/multitarget.md
docs/blog/envd-on-remote-serve.md
docs/developers/kubernetes.md
docs/lang/python.md

docs: fix typos

---

docs/faq/comparison.md

Fix minor grammar errors

---

docs-zh/lang/python.md
docs-zh/netlify.toml
docs/api/cli/cli.md
docs/lang/python.md
docs/netlify.toml
hack/cli/generate-cli-ref.go
package.json
pnpm-lock.yaml
pnpm-workspace.yaml

- use LTS version https://nodejs.org/en

fix: netlify node version & build errors

---

docs-zh/teams/cache.md
docs/teams/cache.md

- related to https://github.com/tensorchord/envd/issues/1974

add builder warning for cache
